version: '3.8'

services:
  traefik-atlas-frontend:
    image: traefik:v2.10
    container_name: traefik-atlas-frontend
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=frxncismor@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web
    restart: unless-stopped

  watchtower-atlas-frontend:
    image: containrrr/watchtower
    container_name: watchtower-atlas-frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    restart: unless-stopped

  atlas-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frxncis/atlas-frontend:latest
    container_name: atlas-frontend
    environment:
      - NODE_ENV=production
      - STRIPE_PRIVATE_API_KEY=${STRIPE_PRIVATE_API_KEY}
      - STRIPE_PUBLIC_API_KEY=${STRIPE_PUBLIC_API_KEY}
    expose:
      - "4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atlas-frontend.rule=Host(`atlas.digitalparty.com`)"
      - "traefik.http.routers.atlas-frontend.entrypoints=websecure"
      - "traefik.http.services.atlas-frontend.loadbalancer.server.port=4000"
      - "traefik.http.routers.atlas-frontend.tls.certresolver=myresolver"
    networks:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web:
    external: true